### ISSUE TITLE
SibauiRP-ALTV

### ISSUE THREAD

**Issue by mikami1337** [E6IIRA/SIbauiRP-ALTV#1]
Kannst du mir bei aufsetzen helfen oder kannst du mir es aufsetzen würdest dafür auch Geld kriegen würde mich freuen.

Discord:Ifzoom#1570

**Comment by E6IIRA** [comment]
> Kannst du mir bei aufsetzen helfen oder kannst du mir es aufsetzen würdest dafür auch Geld kriegen würde mich freuen.
> 
> Discord:Ifzoom#1570

Discord : Polstar#3824
